twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ["bootstrap_5_layout.html.twig"]
    globals:
        chemin_couvertures: "/images/couvertures/"
        chemin_images: "/images/"

when@test:
    twig:
        strict_variables: true
